[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "kernel"
path = "src/main.rs"
test = false
bench = false

[features]
default = []
qemu-test = []

[dependencies]
bootloader_api = "0.11.15"
lazy_static = { version = "1.5", features = ["spin_no_std"] }
noto-sans-mono-bitmap = { version = "0.2.0", default-features = false, features = [
    "regular",
    "size_16",
    "unicode-basic-latin",
] }
pc-keyboard = "0.9"
pic8259 = { version = "0.11", default-features = false }
spin = "0.10"
uart_16550 = "0.3"
x86_64 = { version = "0.15.5", default-features = false, features = [
    "abi_x86_interrupt",
    "instructions",
] }
