pub(crate) mod acpi;
pub(crate) mod ap_trampoline;
pub(crate) mod apic;
pub(crate) mod gdt;
pub(crate) mod hpet;
pub(crate) mod interrupts;
pub(crate) mod ipi;
pub(crate) mod smp_bringup;
pub(crate) mod smp_runtime;
#[path = "../../smp_scheduler.rs"]
pub(crate) mod smp_scheduler;
