[package]
name = "mkfs-nullfs"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
repository = "https://github.com/LotusPetal392/nullstar-os"

[dependencies]
nullfs-blockdev = { path = "../../crates/nullfs-blockdev", features = ["std"] }
nullfs-core = { path = "../../crates/nullfs-core" }
nullfs-format = { path = "../../crates/nullfs-format" }
nullfs-testkit = { path = "../../crates/nullfs-testkit" }
