[package]
name = "userspace"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[[bin]]
name = "init"
path = "src/main.rs"
test = false
bench = false

[[bin]]
name = "fault_probe"
path = "src/bin/fault_probe.rs"
test = false
bench = false

[[bin]]
name = "cat"
path = "src/bin/cat.rs"
test = false
bench = false

[[bin]]
name = "readline"
path = "src/bin/readline.rs"
test = false
bench = false
